version: '2'
services:
    something-app:
        image: something
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://something-mysql:3306/something?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    something-mysql:
        extends:
            file: mysql.yml
            service: something-mysql
